"""Add ContactSubmission model

Revision ID: 01418a376da0
Revises: bc597f1a6ae0
Create Date: 2025-09-27 01:47:55.244974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01418a376da0'
down_revision = 'bc597f1a6ae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_email', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_submission')
    # ### end Alembic commands ###
